- name: Set hostname and timezone
  hosts: all
  #become: yes

  tasks:
    - name: Set hostname using hostnamectl
      become: true
      shell: "hostnamectl set-hostname {{ inventory_hostname }}"
      register: hostname_result
    
    - name: change timezone to Ho Chi Minh
      become: true
      shell: "timedatectl set-timezone Asia/Ho_Chi_Minh"
      register: timezone_result